1. Импорт библиотеки NumPy с общепринятым сокращением (`import numpy as np`).

In [1]:
import numpy as np

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [2]:
a = np.array([[1, 6, 8],
             [7, -4, 2]]) #создание двумерного массива (матрицу) 2 на 3
b = np.zeros((2,4,1)) # создание трехмерного массива 2 на 4 на 1 из нулей
c = np.arange(11, 17, 0.5) #создание строки с элементами от 11 до 17, не включая, и с шагом 0.5 
d = np.linspace(23, 28, 10) #создание строки из 10 равномерно заполненных элементов в диапозоне от 23 до 28, включая
e = np.diag([3,7,-2,5]) #создание диагональной матрицы с значениями из переданного массива в параметре 

print(a,b,c,d,e, sep='\n\n')

[[ 1  6  8]
 [ 7 -4  2]]

[[[0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]]]

[11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5]

[23.         23.55555556 24.11111111 24.66666667 25.22222222 25.77777778
 26.33333333 26.88888889 27.44444444 28.        ]

[[ 3  0  0  0]
 [ 0  7  0  0]
 [ 0  0 -2  0]
 [ 0  0  0  5]]


3. Демонстрация атрибутов:
   - вывод формы (`shape`) и типа данных (`dtype`) для одного из массивов.

In [3]:
c.shape, c.dtype #массив с - одномерная массив (строка) из 12 элементов, тип данных масива c - float64

((12,), dtype('float64'))

4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [4]:
a[1,1] #получение отдельного элемента из двумерного массива из 2 строки и 2 столбца

np.int64(-4)

In [5]:
e[[2], 1:4] #получение подмассива 3 строки матрицы e длиною 3 с помощью среза, состоящего из элементов с индексами 1, 2 и 3

array([[ 0, -2,  0]])

5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [6]:
example1 = np.eye(2,3) #создание единичной матрицы 2 на 3
a * example1 #умножение единичной матрицы example1 на матрицу a

array([[ 1.,  0.,  0.],
       [ 0., -4.,  0.]])

In [7]:
example2 = np.vsplit(np.hsplit(e, [3])[0], 2)[0] #вертикально у горизонтпльное обрезание матрицы е до формы 2 на 3
a + example2 #сложение матрицы а и е

array([[4, 6, 8],
       [7, 3, 2]])

In [8]:
#массив cars содержит данные о скорости(км/ч), расходе топлива(л/100км) и времени эксплуатации(лет), распределенные по столбцам соответсвтенно 
cars = np.array([
    [120, 8.5, 3],
    [150, 9.2, 5],
    [100, 7.8, 2],
    [130, 8.9, 4],
    [110, 8.0, 3]
])

average_features = cars.mean(axis=0)
print("Среднее по показателям (скорость, расход, возраст):", average_features)

feature_min = cars.min(axis=0)
print("Минимум по показателям:", feature_min)

feature_max = cars.max(axis=0)
print("Максимум по показателям:", feature_max)

feature_std = cars.std(axis=0)
print("Стандартное отклонение по показателям:", feature_std)

Среднее по показателям (скорость, расход, возраст): [122.     8.48   3.4 ]
Минимум по показателям: [100.    7.8   2. ]
Максимум по показателям: [150.    9.2   5. ]
Стандартное отклонение по показателям: [17.20465053  0.52687759  1.0198039 ]
